[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "7b0c1508ceefcf57360db755452314fc9311ad54"}
