[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "nightly"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "add16e97388a486a25569d8a905d29b5c293f3fb"}
